apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-db-pvc
  namespace: ecommerce
spec:
  accessModes: ['ReadWriteOnce']
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-db
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-db
  template:
    metadata:
      labels:
        app: payment-db
    spec:
      containers:
        - name: payment-db
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef: { name: payment-db-secret, key: POSTGRES_USER }
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef: { name: payment-db-secret, key: POSTGRES_PASSWORD }
            - name: POSTGRES_DB
              value: payment_db
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ['pg_isready', '-U', 'postgres']
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: payment-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: payment-db
  namespace: ecommerce
spec:
  selector:
    app: payment-db
  ports:
    - port: 5432
      targetPort: 5432
