apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ecommerce
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s

    scrape_configs:
      - job_name: order-service
        metrics_path: /metrics
        static_configs:
          - targets: ['order-service:3001']
      - job_name: payment-service
        metrics_path: /metrics
        static_configs:
          - targets: ['payment-service:3002']
      - job_name: inventory-service
        metrics_path: /metrics
        static_configs:
          - targets: ['inventory-service:3003']
      - job_name: auth-service
        metrics_path: /metrics
        static_configs:
          - targets: ['auth-service:3004']
      - job_name: catalog-service
        metrics_path: /metrics
        static_configs:
          - targets: ['catalog-service:3005']
      - job_name: notification-service
        metrics_path: /metrics
        static_configs:
          - targets: ['notification-service:3006']
      - job_name: gateway-service
        metrics_path: /metrics
        static_configs:
          - targets: ['gateway-service:3000']
      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.53.0
          args:
            - '--config.file=/etc/prometheus/prometheus.yml'
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
          resources:
            requests: { memory: '200Mi', cpu: '100m' }
            limits: { memory: '400Mi', cpu: '500m' }
          readinessProbe:
            httpGet: { path: /-/ready, port: 9090 }
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: ecommerce
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
